apiVersion: v1
kind: Pod
metadata:
 name: app
 labels:
  name: app
spec:
  containers:
  - name: http-echo
    image: iamdevil1430/sunnysapp
    args:
      - "--text=hello world 1"
      - "--addr=:80"
---
apiVersion: v1
kind: Pod
metadata:
 name: app2
 labels:
  name: app2
spec:
  containers:
  - name: http-echo
    image: iamdevil1430/sunnysapp
    args:
      - "--text=hello world 2"
      - "--addr=:80"


