apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
    template:
      metadata:
        labels:
          app: app1
      spec:
        containers:
        - name: my-container
        image: iamdevil1430/sunnysapp
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata: 
  name: demo-svc
spec:
  selector:
    app.kubernetes.io/name: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

