apiVersion: v1
kind: Pod
metadata:
 name: app1
 labels:
  name: app1
spec:
  containers:
  - name: http-echo
    image: iamdevil1430/sunnysapp
    ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
 name: app2
 labels:
  name: app2
spec:
  containers:
  - name: http-echo
    image: iamdevil1430/sunnysapp
    ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata: 
  name: demo-svc
spec:
  selector:
    name: app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

